name: Feature request
description: Propose a feature
labels: ["needs triage"]
body:

  - type: textarea
    attributes:
      label: 🚀 Feature description
      description: A clear and concise description of the feature you want
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: >
        Why do you want/need this feature? Is your feature request related to a problem? For example, I'm always frustrated when [...]. If this is related to another GitHub issue, please link it here
    validations:
      required: true

  - type: textarea
    attributes:
      label: Pitch
      description: >
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: >
        A clear and concise description of any alternative solutions or features you've considered, if any.
    validations:
      required: true

- type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
