name: Probot

on:
  check_run:
  pull_request:
  workflow_dispatch:

jobs:
  required-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: carmocca/probot@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
